version: '3.9'

services:

  erp-database:
    image: postgres:16
    container_name: erp-database
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cesi
    networks:
      - webnet
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 5s
      retries: 8

  erp-front:
    container_name: erp-front
    image: cesi-erp-front-end:latest
    build:
      context: .
      dockerfile: ./front/dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Lecture seule pour le fichier de configuration
    networks:
      - webnet
    restart: always # Redémarre toujours le conteneur en cas de crash
    security_opt:
      - no-new-privileges:true # Empêche l'élévation des privilèges


  erp-back:
    image: cesi-erp-back-end:latest
    container_name: erp-back
    environment:
      - NODE_ENV=production
      - DB_IP=erp-database
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
      - DB_DATABASE_NAME=cesi
    env_file:
      - ./back/.env
    build:
      context: .
      dockerfile: ./back/dockerfile
    ports:
      - "8080:8080"
    networks:
      - webnet
    depends_on:
      erp-database:
        condition: service_healthy

networks:
  webnet:
    driver: bridge
